### ISSUE TITLE
Source code jar is missing

### ISSUE THREAD

**Issue by rickb777** [hmrc/http-verbs#41]
As a user of http-verbs, I have my project open in IntelliJ but I cannot browse the source code without wasting time finding out which repo it is in, then only having web-page views of the source code (i.e. not clickable content within IntelliJ).

Can you provide the source jars automatically?

**Comment by colin-lamed** [comment]
source-jars are published to [open-artefacts](https://open.artefacts.tax.service.gov.uk/maven2/uk/gov/hmrc/http-verbs-play-28_2.12/13.9.0/http-verbs-play-28_2.12-13.9.0-sources.jar)
